### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by suiniara** [764664/v2ray-electron#12]
os: windwos10
version: V2Ray-Electron-Setup-0.14.0.exe
error reporting

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: o(...).default is not a constructor
    at Object.<anonymous> (C:\Users\CONSTELLATION39\AppData\Local\Programs\v2ray-electron\resources\app.asar\main.js:1:5737)
    at __webpack_require__ (C:\Users\CONSTELLATION39\AppData\Local\Programs\v2ray-electron\resources\app.asar\webpack:\webpack\bootstrap:9:1)
    at Object.<anonymous> (C:\Users\CONSTELLATION39\AppData\Local\Programs\v2ray-electron\resources\app.asar\main.js:1:1671)
    at __webpack_require__ (C:\Users\CONSTELLATION39\AppData\Local\Programs\v2ray-electron\resources\app.asar\webpack:\webpack\bootstrap:9:1)
    at Object.<anonymous> (C:\Users\CONSTELLATION39\AppData\Local\Programs\v2ray-electron\resources\app.asar\main.js:1:1558)
    at __webpack_require__ (C:\Users\CONSTELLATION39\AppData\Local\Programs\v2ray-electron\resources\app.asar\webpack:\webpack\bootstrap:9:1)
    at Object (C:\Users\CONSTELLATION39\AppData\Local\Programs\v2ray-electron\resources\app.asar\webpack:\webpack\bootstrap:76:63)
    at Object.<anonymous> (C:\Users\CONSTELLATION39\AppData\Local\Programs\v2ray-electron\resources\app.asar\webpack:\webpack\bootstrap:79:1)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)

**Comment by jie-lyu** [comment]
Thanks for the feedback. v0.15.0 was just released to fix this issue. Could you try it?

**Comment by suiniara** [comment]
sure, now it doesn't go wrong
